#!/usr/bin/env node
// One version, four places. package.json is the source of truth; this keeps the Tauri config, the Rust crate
// and the page's version.js in step, so every edition (server, static, exe, desktop) reports the same number.
//
//   node tools/bump.js            show the current version and whether every file agrees
//   node tools/bump.js patch      1.17.1 -> 1.17.2      (also: minor, major)
//   node tools/bump.js 2.0.0      set an exact version
//   node tools/bump.js --sync     rewrite the other files from package.json without changing the number
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const files = {
  pkg: path.join(root, 'package.json'),
  tauri: path.join(root, 'src-tauri', 'tauri.conf.json'),
  cargo: path.join(root, 'src-tauri', 'Cargo.toml'),
  page: path.join(root, 'public', 'version.js'),
};
// every <span class="nd-version">x.y.z</span> in these pages (the manual quotes the version in several places)
const docs = ['manual.html', 'cheatsheet.html', 'index.html'].map((f) => path.join(root, 'public', f)).filter((f) => fs.existsSync(f));
const SPAN = /(<span class="nd-version">)[^<]*(<\/span>)/g;
const read = (f) => fs.readFileSync(f, 'utf8');
const current = () => JSON.parse(read(files.pkg)).version;
const found = () => ({
  'package.json': current(),
  'tauri.conf.json': JSON.parse(read(files.tauri)).version,
  'Cargo.toml': (read(files.cargo).match(/^version = "([^"]+)"/m) || [])[1],
  'version.js': fs.existsSync(files.page) ? (read(files.page).match(/'([^']+)'/) || [])[1] : '(missing)',
  ...Object.fromEntries(docs.map((f) => { const all = [...read(f).matchAll(/<span class="nd-version">([^<]*)<\/span>/g)].map((x) => x[1]); return all.length ? [path.basename(f) + ' (' + all.length + ')', [...new Set(all)].join(' / ')] : null; }).filter(Boolean)),
});

function next(arg) {
  const v = current();
  if (/^\d+\.\d+\.\d+$/.test(arg)) return arg;
  const [a, b, c] = v.split('.').map(Number);
  if (arg === 'patch') return `${a}.${b}.${c + 1}`;
  if (arg === 'minor') return `${a}.${b + 1}.0`;
  if (arg === 'major') return `${a + 1}.0.0`;
  throw new Error(`Not a version or patch/minor/major: ${arg}`);
}

function write(v) {
  const setJson = (f) => { const s = read(f); fs.writeFileSync(f, s.replace(/"version":\s*"[^"]+"/, `"version": "${v}"`)); };
  setJson(files.pkg);
  setJson(files.tauri);
  fs.writeFileSync(files.cargo, read(files.cargo).replace(/^version = "[^"]+"/m, `version = "${v}"`));
  for (const f of docs) { const s = read(f); if (SPAN.test(s)) fs.writeFileSync(f, s.replace(SPAN, `$1${v}$2`)); SPAN.lastIndex = 0; }
  fs.writeFileSync(files.page, `// Generated by tools/bump.js — do not edit; run "node tools/bump.js" instead.\nwindow.NETDECK_VERSION = '${v}';\n`);
}

const arg = process.argv[2];
if (!arg) {
  const f = found();
  const agree = new Set(Object.values(f)).size === 1;
  console.log(`NetDeck ${f['package.json']}`);
  for (const [k, v] of Object.entries(f)) console.log(`  ${k.padEnd(20)} ${v}${v === f['package.json'] ? '' : '   <-- differs'}`);
  if (!agree) { console.log('Files disagree: run "node tools/bump.js --sync".'); process.exit(1); }
} else if (arg === '--sync') {
  write(current());
  console.log(`synced all files to ${current()}`);
} else {
  const v = next(arg);
  write(v);
  console.log(`${found()['package.json']} — package.json, tauri.conf.json, Cargo.toml, public/version.js and the version in the manual updated`);
}
