#!/usr/bin/env node
// Writes the "About & license" section at the end of public/manual.html: NetDeck's own MIT license, and the
// third-party components the desktop app is built from, grouped by license (from `cargo metadata`).
//
//   node tools/licenses.js        re-run after dependency updates; it replaces the section in place
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const root = path.join(__dirname, '..');
const manual = path.join(root, 'public', 'manual.html');
const esc = (s) => String(s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));

const meta = JSON.parse(execFileSync('cargo', ['metadata', '--format-version', '1', '--locked'], { cwd: path.join(root, 'src-tauri'), maxBuffer: 64 * 1024 * 1024 }).toString());
const inGraph = new Set(meta.resolve.nodes.map((n) => n.id));
const crates = meta.packages.filter((p) => inGraph.has(p.id) && p.name !== 'netdeck');
// "MIT/Apache-2.0" and "Apache-2.0 OR MIT" are the same choice: normalize the spelling before grouping
const norm = (l) => (l || 'see the crate').replace(/\s*\/\s*/g, ' OR ').split(/\s+OR\s+/).map((x) => x.trim()).sort().join(' OR ');
const groups = new Map();
for (const c of crates) { const l = norm(c.license); if (!groups.has(l)) groups.set(l, []); groups.get(l).push(`${c.name} ${c.version}`); }
const sorted = [...groups.entries()].sort((a, b) => b[1].length - a[1].length);
const year = new Date().getFullYear();
const version = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8')).version;

const section = `<!-- about:start (generated by tools/licenses.js) -->
<h2 id="about">About &amp; license</h2>
<p>NetDeck <span class="nd-version">${esc(version)}</span> — a network &amp; system command reference with live execution and guided playbooks. Source code, releases and issue tracker: <a href="https://github.com/DavidKFisk/netdeck">github.com/DavidKFisk/netdeck</a>.</p>

<h3 id="license">License</h3>
<p>NetDeck is free software under the MIT License. In short: you may use, copy, change and pass it on, including commercially, as long as the copyright notice and this license text go with it — and it comes with no warranty of any kind. The full text:</p>
<pre class="license">MIT License

Copyright (c) ${year} David Fisk

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.</pre>
<p>The desktop installer shows this license before installing; the same text ships as <code>LICENSE</code> with the source.</p>
<p>NetDeck runs diagnostic commands on your own computer and network. Its verdicts are aids to judgment, not guarantees: a clean result does not prove a network is secure.</p>

<h3 id="third-party">Third-party components</h3>
<p>NetDeck stands on other people's work. Their licenses allow this use; their copyright notices belong to their authors.</p>
<ul>
  <li><strong>Tauri</strong> (desktop app framework) and the Rust libraries it is built from — ${crates.length} crates, listed by license below. Most offer a choice of MIT or Apache-2.0.</li>
  <li><strong>Microsoft Edge WebView2</strong> — the browser engine that draws the desktop app's window; part of Windows, under Microsoft's own terms.</li>
  <li><strong>IEEE MAC address registry</strong> (MA-L, MA-M, MA-S) — the manufacturer names in the network scan; public data published by the IEEE Registration Authority.</li>
  <li><strong>IBM Plex Mono and IBM Plex Sans</strong> — the typefaces, © IBM Corp.; included with NetDeck, unmodified, under the SIL Open Font License 1.1 (the license text ships beside them as <code>fonts/OFL.txt</code>).</li>
  <li><strong>Windows tools</strong> (ipconfig, netsh, pktmon, PowerShell and the rest) — NetDeck runs the copies already on your computer; it does not include or redistribute them.</li>
  <li>The local-server and hosted editions (<code>server.js</code>, the web page) use no third-party packages — only the same fonts and manufacturer list.</li>
</ul>
<table class="licenses">
  <thead><tr><th>License (any one of)</th><th>Crates</th></tr></thead>
  <tbody>
${sorted.map(([l, list]) => `    <tr><td>${esc(l)}</td><td><details><summary>${list.length}</summary><span class="crate-list">${esc(list.sort().join(', '))}</span></details></td></tr>`).join('\n')}
  </tbody>
</table>
<p class="dim-note">Generated from the desktop app's <code>Cargo.lock</code>; each crate's own license and notices ship in its source on <a href="https://crates.io">crates.io</a>.</p>
<!-- about:end -->
`;

let html = fs.readFileSync(manual, 'utf8');
if (html.includes('<!-- about:start')) html = html.replace(/<!-- about:start[\s\S]*?<!-- about:end -->\n/, section);
else {
  if (!html.includes('</main>')) throw new Error('no </main> in manual');
  html = html.replace('</main>', section + '</main>');
}
if (!html.includes('href="#about"')) html = html.replace('      <li><a href="#keys">Keyboard shortcuts</a></li>', '      <li><a href="#keys">Keyboard shortcuts</a></li>\n      <li><a href="#about">About &amp; license</a></li>');
if (!html.includes('table.licenses')) html = html.replace('</style>', `  pre.license { font-size: 12px; white-space: pre-wrap; }
  table.licenses { border-collapse: collapse; width: 100%; font-size: 13px; margin: 8px 0; }
  table.licenses th, table.licenses td { border: 1px solid var(--border-soft); padding: 5px 8px; text-align: left; vertical-align: top; }
  table.licenses td:first-child { font-family: var(--mono); white-space: nowrap; }
  table.licenses summary { cursor: pointer; }
  .crate-list { display: block; margin-top: 4px; color: var(--muted); font-size: 12px; line-height: 1.5; }
  .dim-note { color: var(--muted); font-size: 13px; }
</style>`);
fs.writeFileSync(manual, html);
console.log(`about section written: ${crates.length} crates in ${sorted.length} license groups`);
